library(dplyr)
path <- "./household_power_consumption.txt"
file <- read.table(path,sep=";",header=T)
file <- tbl_df(file)
file$Sub_metering_1 <- as.numeric(file$Sub_metering_1)
file$Sub_metering_2 <- as.numeric(file$Sub_metering_2)
file$Sub_metering_3 <- as.numeric(file$Sub_metering_3)
file <- subset(file,Date %in% c("1/2/2007","2/2/2007"))
date <- as.Date(file$Date,format="%d/%m/%y")
datetime <- paste(date,file$Time)
file$datetime <- as.POSIXlt(datetime)
with(file,plot(datetime,Sub_metering_1,type="l",xlab="",ylab="Energy Sub Metering"))
lines(file$datetime,file$Sub_metering_2,col="red")
lines(file$datetime,file$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),lty=1,lwd=2,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png",height=480,width=480)
dev.off()
